spring.application.name=dangkyhocphan
server.port=8008
spring.datasource.url=jdbc:mariadb://localhost:3307/duandanglyhocphan
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jwt.SIGNER_KEY=ef0344c0be8dea5e70a36a66997060738a4761371ca25d276c1ab4afb9e87f1b
spring.jwt.valid_duration=24
spring.jwt.refreshable_duration=72